version: '3.8'
services:
  price-monitor:
    build: '.'
    container_name: 'price-monitor'
    volumes:
      - './Source:/app/source'
      - './Templates:/app/templates'
      - './Source/db/prices.db:/app/source/db/prices.db'
    ports:
      - '5000:5000'
    restart: 'unless-stopped'
    environment:
      - 'EMAIL_USER=pricemonitor.alert@gmail.com'
      - 'EMAIL_PASS=Ag2015++'
    user: '1000:100'