# Utilizar una imagen base oficial de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el archivo requirements.txt al contenedor
COPY Source/requirements.txt requirements.txt

# Instalar las dependencias necesarias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto de los archivos de la aplicación al contenedor
COPY Source/pricesApp.py pricesApp.py
COPY Templates templates

# Exponer el puerto en el que correrá la aplicación
EXPOSE 5000

# Comando por defecto para ejecutar la aplicación
CMD ["python", "pricesApp.py"]