# Usar una imagen base oficial de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el archivo de requisitos y instalar dependencias
COPY ./Source/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copiar todo el contenido necesario al contenedor
COPY ./Source /app/source
COPY ./Templates /app/templates

# Exponer el puerto necesario para la aplicación
EXPOSE 5000

# Comando por defecto para ejecutar la aplicación
CMD ["python", "/app/source/pricesApp.py"]