# Usar una imagen base de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo de requisitos y el script al contenedor
COPY requirements.txt requirements.txt
COPY app.py app.py
COPY templates templates

# Instalar las dependencias
RUN pip install -r requirements.txt

# Comando para ejecutar el script
CMD ["python", "app.py"]